# Generated by Django 4.2.7 on 2023-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('title', models.CharField(max_length=40)),
                ('excerpt', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
